# This is a basic workflow to help you get started with Actions

name: build-latex

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout previous to $GITHUB_WORKSPACE/previous
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          path: 'previous'
          refs: 'HEAD^'
#      - run: git checkout HEAD^
          
      - name: checkout specific commit to $GITHUB_WORKSPACE/specific
        uses: actions/checkout@v2
        with:
          path: 'specific'

      - name: run normal diff for previous and specific
        run: diff $GITHUB_WORKSPACE/previous $GITHUB_WORKSPACE/specific
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world - $PWD - !

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $PWD
          ls -lisaR
