# This is a basic workflow to help you get started with Actions

name: latexdiff

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  do-latexdiff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make ImageMagick permissive
        run: sudo sed -i 's/rights==".*"/rights="all"/' /etc/ImageMagick-6/policy.xml
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
        
      - name: Compile differential documents
        uses: DanySK/auto-latexdiff@27.20210831.1518
      
      - name: Autotag
        uses: DanySK/semver-autotag-action@0.1.0
