# This is a basic workflow to help you get started with Actions

name: My LaTeX diff

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  My-LaTeX-Diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # install latexdiff
      - name: Install latexdiff
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexdiff
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout version which triggered workflow
        uses: actions/checkout@v2
        with:
          path: trigger
          fetch-depth: 0

      - name: Checkout submitted version
        run: |
          ls
          mkdir submitted
          cd trigger
          git checkout 1e8150e4cfabe8049423b469704e56310e6fd2f7
          cp -r doc ../submitted
          git switch -
          
      # run latexdiff
      - name: Check latexdiff version
        run: latexdiff --flatten submitted/doc/main.tex trigger/doc/main.tex > diff2submitted.tex
        
      # build PDF with differences
      - name: Build PDF with differences
        uses: xu-cheng/latex-action@v2
        with:
          root_file: diff2submitted.tex
          args: "-output-directory=build -pdf"
          latexmk_shell_escape: true
