# This is a basic workflow to help you get started with Actions

name: My LaTeX diff

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  My LaTeX Diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # install latexdiff
      - name: Install latexdiff
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexdiff
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # check latexdiff version
      - name: Check latexdiff version
        run: latexdiff --version
